### ISSUE TITLE
phf_map! on &'static [T; N] broken

### ISSUE THREAD

**Issue by sp3d** [sfackler/rust-phf#84] opened 2016-05-24 00:55 UTC
I guess this is a result of issue #76 but it's no longer possible to use phf_map! with b"foo" syntax to get a `phf::Map<&'static [u8; 3], T>`. Using `&'static [1, 2, 3]` gives an ICE. `[1, 2, 3]` works but loses readability for ASCII byte blobs.

```
#![feature(plugin)]
#![plugin(phf_macros)]

extern crate phf;
extern crate phf_macros;

/* used to work, now type error */
static MAP1: phf::Map<&'static [u8; 3], usize> = phf_map! {
    b"foo" => 2,
};

/* it would be nice if this would work */
static MAP2: phf::Map<[u8; 3], usize> = phf_map! {
    *b"foo" => 2,
};

/* error: internal compiler error: Error constructed but not emitted */
static MAP3: phf::Map<&'static [u8; 3], usize> = phf_map! {
    &'static [4, 3, 2] => 2,
};

/* works */
static MAP4: phf::Map<[u8; 3], usize> = phf_map! {
    [4, 3, 2] => 2,
};
```

**Comment by abonander** [comment] 2019-07-03 19:08
@sp3d it's been quite a while since this issue was opened. Try the latest release version? I can't reproduce the error.

**Comment by abonander** [comment] 2019-07-05 20:45
Closing this as not reproducible (`phf_macros` isn't even a compiler plugin anymore)

**Closed by abonander** 2019-07-05 20:45 UTC
